export default{
  
    "login": "ZelionP",
    "id": 89801600,
    "node_id": "MDQ6VXNlcjg5ODAxNjAw",
    "avatar_url": "https://avatars.githubusercontent.com/u/89801600?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ZelionP",
    "html_url": "https://github.com/ZelionP",
    "followers_url": "https://api.github.com/users/ZelionP/followers",
    "following_url": "https://api.github.com/users/ZelionP/following{/other_user}",
    "gists_url": "https://api.github.com/users/ZelionP/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ZelionP/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ZelionP/subscriptions",
    "organizations_url": "https://api.github.com/users/ZelionP/orgs",
    "repos_url": "https://api.github.com/users/ZelionP/repos",
    "events_url": "https://api.github.com/users/ZelionP/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ZelionP/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Redon",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": "RednoxB",
    "public_repos": 10,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2021-08-30T17:29:26Z",
    "updated_at": "2022-05-16T18:38:06Z"
  
}